# Generated by Django 4.1.13 on 2024-03-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
    ]
