# Generated by Django 4.1.13 on 2024-03-19 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0008_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAuth.user')),
                ('nom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_user_name', to='userAuth.user')),
            ],
        ),
    ]
