# Generated by Django 4.1.13 on 2024-03-20 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0009_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='nom_user',
        ),
    ]
