# Generated by Django 4.1.13 on 2024-03-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0010_remove_contact_nom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='temoinage',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
