# Generated by Django 4.1.13 on 2024-03-22 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0011_temoinage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id_user',
        ),
    ]
