# Generated by Django 4.1.13 on 2024-03-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0012_remove_blog_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temoinage',
            name='user_id',
        ),
    ]
