# Generated by Django 4.1.13 on 2024-03-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0014_remove_contact_id_user_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default='', max_length=100),
        ),
    ]
