# Generated by Django 4.1.13 on 2024-03-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0015_remove_contact_description_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='blog_images/'),
        ),
    ]
