# Generated by Django 4.1.13 on 2024-03-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0005_alter_property_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('idImage', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('image', models.BinaryField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Property.property')),
            ],
        ),
    ]
