# Generated by Django 4.1.13 on 2024-03-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0006_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='category_id',
            new_name='category',
        ),
    ]
