# Generated by Django 4.1.13 on 2024-03-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0007_rename_category_id_property_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
