# Generated by Django 4.1.13 on 2024-03-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0012_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='property_images/'),
        ),
    ]
