# Generated by Django 4.1.13 on 2024-03-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0013_alter_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
    ]
