# Generated by Django 4.1.13 on 2024-03-26 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0015_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_service', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Property.service'),
        ),
    ]
