# Generated by Django 4.1.13 on 2024-02-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_titre', models.CharField(max_length=255)),
                ('property_description', models.TextField()),
                ('property_surface', models.IntegerField()),
                ('property_despon', models.CharField(max_length=255)),
                ('property_prix', models.IntegerField()),
                ('property_photo', models.ImageField(upload_to='property_photos/')),
            ],
        ),
    ]
